version: "3.3"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ../www/teacher_planner:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ioc
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: