INSERT IGNORE INTO course (id, name, cicle) VALUES (1, '1er', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (2, '2on', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (3, '3er', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (4, '4rt', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (5, '5è', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (6, '6è', 'Primaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (7, '1er', 'Secundaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (8, '2on', 'Secundaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (9, '3er', 'Secundaria');
INSERT IGNORE INTO course (id, name, cicle) VALUES (10, '4rt', 'Secundaria');
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(1,'Matemàtiques 1ºESO',7,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(2,'Llengua 1ºESO',7,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(3,'Anglès 1ºESO',7,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(4,'Biologia 1ºESO',7,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(5,'Plàstica 1ºESO',7,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(6,'Tutoria 1ºESO',7,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(7,'Francès 1ºESO',7,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(8,'Tecnologia 1ºESO',7,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(9,'Educació Física 1ºESO',7,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(10,'Socials 1ºESO',7,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(11,'Religió 1ºESO',7,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(12,'Matemàtiques 2ºESO',8,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(13,'Llengua 2ºESO',8,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(14,'Anglès 2ºESO',8,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(15,'Tutoria 2ºESO',8,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(16,'Francès 2ºESO',8,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(17,'Educació Física 2ºESO',8,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(18,'Socials 2ºESO',8,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(19,'Religió 2ºESO',8,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(20,'Música 2ºESO',8,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(21,'Cultura Científica 2ºESO',8,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(22,'Física i Química 2ºESO',8,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(23,'Matemàtiques 3ºESO',9,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(24,'Llengua 3ºESO',9,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(25,'Anglès 3ºESO',9,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(26,'Tutoria 3ºESO',9,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(27,'Francès 3ºESO',9,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(28,'Educació Física 3ºESO',9,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(29,'Socials 3ºESO',9,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(30,'Religió 3ºESO',9,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(31,'Música 3ºESO',9,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(32,'Física i Química 3ºESO',9,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(33,'Tecnologia 3ºESO',9,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(34,'Biologia 3ºESO',9,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(35,'Matemàtiques 4ºESO',10,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(36,'Llengua 4ºESO',10,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(37,'Anglès 4ºESO',10,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(38,'Tutoria 4ºESO',10,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(39,'Francès 4ºESO',10,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(40,'Educació Física 4ºESO',10,2);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(41,'Socials 4ºESO',10,3);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(42,'Religió 4ºESO',10,1);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(43,'Física i Química 4ºESO',10,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(44,'Biologia 4ºESO',10,4);
INSERT IGNORE INTO subject (id, name, course_id, hours_week) VALUES(45,'Informàtica 4ºESO',10,2);
